def generate_auto_attack_guide(final_report: dict) -> str:
    """
    Ultra-readable, bug-bounty-first attack guide.
    No raw data. No noise. Only actionable steps.
    """

    target = final_report.get("target", "target")
    modules = final_report.get("modules", {})
    signals = final_report.get("strategic_summary", {}).get("global_risk_signals", [])

    lines = []

    # =========================
    # Header
    # =========================
    lines.append(f"# 🎯 Automated Bug Bounty Attack Guide")
    lines.append(f"Target: {target}\n")

    if not signals:
        lines.append(
            "## ✅ Result\n"
            "No meaningful security weaknesses were identified through passive analysis.\n"
            "This target does not currently appear promising for bug bounty testing.\n"
        )
        return "\n".join(lines)

    lines.append(
        "## ⚠️ Important\n"
        "Everything below is derived from **passive analysis only**.\n"
        "No exploitation has been performed.\n"
    )

    # =========================
    # Attack Sections
    # =========================

    # ---- IDOR ----
    authz = modules.get("authorization", {})
    if authz.get("worth_deeper_testing"):
        lines.append("\n---\n")
        lines.append("## 🔴 IDOR / Broken Access Control\n")

        lines.append(
            "**Why you should care:**  \n"
            "If object IDs are not properly authorized, you may access other users’ data.\n"
        )

        urls = authz.get("suspicious_object_urls") or authz.get("object_urls") or []

        if urls:
            lines.append("**Start here:**")
            for u in urls[:5]:
                lines.append(f"- {u}")
        else:
            lines.append("**Start here:** Any URL or API call containing numeric or UUID IDs")

        lines.append(
            "\n**What to do (exact steps):**\n"
            "1. Log in as a normal user\n"
            "2. Capture a request containing an ID\n"
            "3. Change the ID and resend the request\n"
        )

        lines.append(
            "**Bug bounty verdict:**  \n"
            "✔ Very likely to produce a valid report if access is granted\n"
        )

    # ---- API ----
    api = modules.get("api_surface", {})
    if api.get("worth_deeper_testing"):
        lines.append("\n---\n")
        lines.append("## 🟠 Public / Weak API Endpoints\n")

        lines.append(
            "**Why you should care:**  \n"
            "Unauthenticated or weak APIs often expose sensitive business logic.\n"
        )

        endpoints = api.get("unauthenticated_api_signals") or api.get("api_endpoints_detected") or []

        if endpoints:
            lines.append("**Start here:**")
            for e in endpoints[:5]:
                lines.append(f"- {e}")

        lines.append(
            "\n**What to do (exact steps):**\n"
            "1. Send requests without authentication\n"
            "2. Remove Authorization headers\n"
            "3. Modify user_id or object references\n"
        )

        lines.append(
            "**Bug bounty verdict:**  \n"
            "✔ Medium–High chance depending on data exposure\n"
        )

    # ---- Client-side ----
    client = modules.get("client_side_js", {})
    if client.get("worth_deeper_testing"):
        lines.append("\n---\n")
        lines.append("## 🟡 Client-Side Trust Issues\n")

        lines.append(
            "**Why you should care:**  \n"
            "Frontend restrictions are sometimes not enforced server-side.\n"
        )

        lines.append(
            "**What to do (exact steps):**\n"
            "1. Observe frontend requests in DevTools\n"
            "2. Replay them manually (Burp / curl)\n"
            "3. Remove or modify restricted parameters\n"
        )

        lines.append(
            "**Bug bounty verdict:**  \n"
            "✔ Situational but often overlooked\n"
        )

    # =========================
    # Final Guidance
    # =========================
    lines.append(
        "\n---\n"
        "## 🧠 Final Advice\n"
        "- Do NOT brute force\n"
        "- Do NOT spray payloads\n"
        "- Follow the steps above exactly\n"
        "- If behavior changes → you have a bug\n"
    )

    lines.append(
        "\n---\n"
        "Generated by SecAI — passive intelligence only.\n"
    )

    return "\n".join(lines)
