from reports.poc_generator import generate_poc_examples
from reports.severity_engine import assess_severity
from reports.report_filter import should_report


def generate_narrative_report(final_report: dict) -> str:
    """
    Converts raw SecAI output into a human-readable,
    bug-bounty-ready attack playbook.
    No raw JSON. No noise. Only actionable guidance.
    """

    lines = []

    target = final_report.get("target", "unknown target")
    strategic = final_report.get("strategic_summary", {})
    risk_signals = strategic.get("global_risk_signals", [])
    high_value = strategic.get("high_value_surfaces", [])
    modules = final_report.get("modules", {})

    # =========================
    # Header
    # =========================
    lines.append(f"# Bug Bounty Attack Playbook for {target}\n")

    if risk_signals:
        lines.append(
            "This playbook highlights **realistic bug bounty attack paths** identified "
            "through passive analysis only. No exploitation was performed.\n"
        )
    else:
        lines.append(
            "No meaningful security weaknesses were identified via passive analysis. "
            "The target appears relatively hardened against common bug bounty vectors.\n"
        )
        return "\n".join(lines)

    # =========================
    # Overall status
    # =========================
    if high_value:
        lines.append("## Overall Status: ⚠️ Manual Security Testing Recommended\n")
    else:
        lines.append("## Overall Status: ✅ No High-Risk Surface Detected\n")

    # =========================
    # Priorities
    # =========================
    lines.append("## What should I test first?\n")

    priorities = []
    for signal in risk_signals:
        s = signal.lower()
        if "idor" in s or "access control" in s:
            priorities.append("Test for IDOR / Broken Access Control")
        if "api" in s:
            priorities.append("Test unauthenticated or weakly protected API endpoints")
        if "cookie" in s:
            priorities.append("Review session handling and cookie security")
        if "csp" in s or "client" in s:
            priorities.append("Inspect client-side trust assumptions")
        if "error" in s:
            priorities.append("Review error handling for information disclosure")

    if priorities:
        for i, p in enumerate(sorted(set(priorities)), 1):
            lines.append(f"{i}. {p}")
    else:
        lines.append("No clear high-impact attack paths identified.")

    # =========================
    # Per-module attack guidance
    # =========================
    for module_name, module in modules.items():
        if not module.get("worth_deeper_testing"):
            continue

        decision = should_report(module_name, module)
        severity = assess_severity(module_name, module)

        lines.append("\n---\n")
        lines.append(f"## 🔍 {module_name.replace('_', ' ').title()}")

        lines.append(f"- **Report Recommendation:** {decision}")
        lines.append(f"- **Estimated Severity:** {severity['level']}")
        lines.append(f"- **Why it matters:** {severity['justification']}")

        urls = (
            module.get("suspicious_object_urls")
            or module.get("api_endpoints_detected")
            or module.get("urls")
            or []
        )

        lines.append("\n### Where to look")
        if urls:
            for u in urls[:10]:
                lines.append(f"- {u}")
        else:
            lines.append("- Requests containing numeric IDs, UUIDs, or user references")

        lines.append(
            "\n### What to try\n"
            "1. Intercept the request with a proxy\n"
            "2. Modify object identifiers or user references\n"
            "3. Replay the request\n"
            "4. Observe unauthorized behavior or data exposure\n"
        )

        lines.append(generate_poc_examples())

    # =========================
    # What NOT worth testing
    # =========================
    lines.append("\n---\n")
    lines.append("## ❌ What is probably NOT worth your time\n")
    lines.append(
        "- Blind brute-force attacks\n"
        "- Legacy SQL injection payloads\n"
        "- Untargeted reflected XSS spraying\n"
    )

    # =========================
    # Footer
    # =========================
    lines.append(
        "\n---\n"
        "_Generated by SECAI from passive intelligence only. "
        "All testing must remain within program scope._"
    )

    return "\n".join(lines)
